// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJqgvy40kqe_EbqDKD-cxovUF7lhhbcIM',
    appId: '1:941522876231:web:aad03cb52219cc3d26be62',
    messagingSenderId: '941522876231',
    projectId: 'evently-app-route',
    authDomain: 'evently-app-route.firebaseapp.com',
    storageBucket: 'evently-app-route.firebasestorage.app',
    measurementId: 'G-CR7GXSPJFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP1jNulIgA69gR30jy2JbLWC75VMCFgyo',
    appId: '1:941522876231:android:fbb6b912eed344c926be62',
    messagingSenderId: '941522876231',
    projectId: 'evently-app-route',
    storageBucket: 'evently-app-route.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FNx5KC7EnraHtL_35nDyagmSo7IeCXY',
    appId: '1:941522876231:ios:24be1b0c0de23a5c26be62',
    messagingSenderId: '941522876231',
    projectId: 'evently-app-route',
    storageBucket: 'evently-app-route.firebasestorage.app',
    androidClientId: '941522876231-g1rl7lnm7s6b4lh3c4b47hgkjh9rv4q1.apps.googleusercontent.com',
    iosClientId: '941522876231-c0t08qou8ujbdv9urc6aclpuh4389f2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJqgvy40kqe_EbqDKD-cxovUF7lhhbcIM',
    appId: '1:941522876231:web:e1270904cf4a481526be62',
    messagingSenderId: '941522876231',
    projectId: 'evently-app-route',
    authDomain: 'evently-app-route.firebaseapp.com',
    storageBucket: 'evently-app-route.firebasestorage.app',
    measurementId: 'G-EWGPVWVQ4B',
  );

}